### ISSUE TITLE
Enhancement: Giphy as featured image

### ISSUE THREAD

**Issue by dartiss** [youknowriad/dropit#8]
Please implement the option to use Giphy for a featured image.

I raised this in #6 for both Unsplash and Giphy. Unsplash has now been implemented for featured images but not Giphy.

**Comment by youknowriad** [comment]
The Giphy API doesn't have a download URL (like Unsplash) which means I'm not certain it's authorized to download the Giphs (because featured images need to be hosted/uploaded to WP to work). We'll have to take a look at their docs.

**Comment by ghost** [comment]
See https://giphy.com/terms. Any gif uploaded on Giphy is considered as a public gif so any use that is related to their services might be authorized but we, as WP plugin, are a third-party for Giphy API, so I don't know if we are part of its services. That could make sense.

In fact I consciously skipped the upload part because I was not very sure of that. Pretty much everything in their API is meant for embed not download.

**Comment by ghost** [comment]
@dartiss @youknowriad The Giphy team confirmed this is not allowed.
